CREATE OR REPLACE VIEW ACCOUNT_SETTINGS_VIEW AS
  SELECT ROWNUM ID, ACT.ACCOUNTID, LATEST_CHANGE, HEIGHT, MULTIPLIER, RECALC_DAY
  FROM ACCOUNTS_ACCOUNTSETTINGS ACT
  JOIN (SELECT ACCOUNTID, MAX(DATE_CHANGED) LATEST_CHANGE
        FROM ACCOUNTS_ACCOUNTSETTINGS
        GROUP BY ACCOUNTID) ACT_I
  ON ACT.ACCOUNTID = ACT_I.ACCOUNTID and ACT.DATE_CHANGED = ACT_I.LATEST_CHANGE;

CREATE OR REPLACE VIEW ACCOUNT_VIEW AS
  SELECT ACT.ID, USERNAME, PASSWORD, BIRTHDAY, GENDER, UNIT_SYSTEM, ACTIVE_SINCE, LATEST_CHANGE, HEIGHT, MULTIPLIER, RECALC
  FROM ACCOUNT ACT
  JOIN ACCOUNT_SETTING_VIEW ASV
  ON ACT.ID = ASV.ACCOUNTID;
  
  
CREATE OR REPLACE VIEW INGREDIENT_VIEW AS
  SELECT I.ID,
         I.NAME INGREDIENT_NAME,
         B.NAME BRAND_NAME,
         C.NAME CATEGORY_NAME,
         SERVING_SIZE,
         U.NAME SERVING_UNIT,
         U.SHORT_NAME SERVING_UNIT_SHORT,
         ALT_SERVING_SIZE,
         U2.NAME ALT_SERVING_UNIT,
         U2.SHORT_NAME ALT_SERVING_UNIT_SHORT,
         CALORIES,
         FAT,
         CARBS,
         PROTEIN
  FROM INGREDIENT I
  INNER JOIN BRAND B ON (I.BRANDID = B.ID)
  INNER JOIN CATEGORY C ON (I.CATEGORYID = C.ID)
  INNER JOIN UNIT U ON (I.SERVING_UNIT = U.ID)
  INNER JOIN UNIT U2 ON (I.ALT_SERVING_UNIT = U2.ID)
  ORDER BY ID;
         