CREATE TABLE BRAND
( ID INTEGER PRIMARY KEY
, NAME VARCHAR2(40)
);

CREATE SEQUENCE SEQ_BRANDID
START WITH 0
MINVALUE 0
INCREMENT BY 1
CACHE 20
NOCYCLE;

-------------------------------------------------------------------------------
-- BRANDS
-------------------------------------------------------------------------------
CREATE OR REPLACE PROCEDURE BRAND_GETALL(PCURSOR OUT SYS_REFCURSOR)
IS
BEGIN
  OPEN PCURSOR FOR
    SELECT *
    FROM BRAND
    ORDER BY NAME;
END;
/

CREATE OR REPLACE PROCEDURE BRAND_GETNAME_BYID
( PID IN BRAND.ID%TYPE
, PCURSOR OUT SYS_REFCURSOR
)
IS
BEGIN
  OPEN PCURSOR FOR 
    SELECT NAME FROM BRAND WHERE ID=PID;
END;
/

CREATE OR REPLACE PROCEDURE BRAND_INSERT
( PNAME BRAND.NAME%TYPE
)
IS
BEGIN
  INSERT INTO BRAND(ID, NAME)
  VALUES(SEQ_BRANDID.NEXTVAL, PNAME);
  COMMIT;
  
  EXCEPTION
   WHEN OTHERS THEN
    ROLLBACK;
    RAISE;
END;
/

CREATE OR REPLACE PROCEDURE BRAND_GET_BYNAME
( PNAME IN BRAND.NAME%TYPE
, PCURSOR OUT SYS_REFCURSOR
)
IS
BEGIN
  OPEN PCURSOR FOR
    SELECT * FROM BRAND WHERE UPPER(NAME)=UPPER(PNAME);
END;
/

-------------------------------------------------------------------------------
-- BRAND INSERTS
-------------------------------------------------------------------------------
EXEC BRAND_INSERT('Isopure');
EXEC BRAND_INSERT('Regal Spring');
EXEC BRAND_INSERT('Food City');
EXEC BRAND_INSERT('Mahatma');
EXEC BRAND_INSERT('Healthy Harvest');
EXEC BRAND_INSERT('Nature''s Own');
EXEC BRAND_INSERT('Chobani');
EXEC BRAND_INSERT('Quaker Oats');