CREATE TABLE CATEGORY
( ID INTEGER PRIMARY KEY
, NAME VARCHAR2(40)
);

CREATE SEQUENCE SEQ_CATEGORYID
START WITH 0
MINVALUE 0
INCREMENT BY 1
CACHE 20
NOCYCLE;

-------------------------------------------------------------------------------
-- CATEGORY
-------------------------------------------------------------------------------
CREATE OR REPLACE PROCEDURE CATEGORY_GETALL(PCURSOR OUT SYS_REFCURSOR)
IS
BEGIN
  OPEN PCURSOR FOR
    SELECT *
    FROM CATEGORY
    ORDER BY NAME;
END;
/

CREATE OR REPLACE PROCEDURE CATEGORY_GETNAME_BYID
( PID IN CATEGORY.ID%TYPE
, PCURSOR OUT SYS_REFCURSOR
)
IS
BEGIN
  OPEN PCURSOR FOR 
    SELECT NAME FROM CATEGORY WHERE ID=PID;
END;
/

CREATE OR REPLACE PROCEDURE CATEGORY_INSERT
( PNAME CATEGORY.NAME%TYPE
)
IS
BEGIN
  INSERT INTO CATEGORY(ID, NAME)
  VALUES(SEQ_CATEGORYID.NEXTVAL, PNAME);
  COMMIT;
  
  EXCEPTION
   WHEN OTHERS THEN
    ROLLBACK;
    RAISE;
END;
/

CREATE OR REPLACE PROCEDURE CATEGORY_GET_BYNAME
( PNAME IN CATEGORY.NAME%TYPE
, PCURSOR OUT SYS_REFCURSOR
)
IS
BEGIN
  OPEN PCURSOR FOR
    SELECT * FROM CATEGORY WHERE UPPER(NAME)=UPPER(PNAME);
END;
/

-------------------------------------------------------------------------------
-- CATEGORY INSERTS
-------------------------------------------------------------------------------
EXEC CATEGORY_INSERT('Proteins');
EXEC CATEGORY_INSERT('Dairy');
EXEC CATEGORY_INSERT('Carbs');
EXEC CATEGORY_INSERT('Other');