CREATE TABLE CATEGORY(NAME VARCHAR2(40), CONSTRAINT PK_CATEGORY_NAME PRIMARY KEY(NAME));

CREATE OR REPLACE PACKAGE CATEGORY_PKG AS
  -- Creates a new category
  PROCEDURE NEW(PNAME IN CATEGORY.NAME%TYPE);
  
  -- Returns a SYS_REFCURSOR for all categories
  PROCEDURE GET(PCURSOR OUT SYS_REFCURSOR);
  
END CATEGORY_PKG;
/

CREATE OR REPLACE PACKAGE BODY CATEGORY_PKG AS
  PROCEDURE NEW(PNAME IN CATEGORY.NAME%TYPE)
  IS
  BEGIN
    INSERT INTO CATEGORY(NAME)
    VALUES(PNAME);
    COMMIT;
    
    EXCEPTION
      WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
  END NEW;
  
  PROCEDURE GET(PCURSOR OUT SYS_REFCURSOR)
  IS
  BEGIN
    OPEN PCURSOR FOR
      SELECT NAME
      FROM CATEGORY;
  END GET; 
  
END CATEGORY_PKG;
/
-------------------------------------------------------------------------------
-- CATEGORY INSERTS
-------------------------------------------------------------------------------
EXEC CATEGORY_PKG.NEW('Proteins');
EXEC CATEGORY_PKG.NEW('Dairy');
EXEC CATEGORY_PKG.NEW('Carbs');
EXEC CATEGORY_PKG.NEW('Other');