CREATE TABLE FORMULA
( NAME VARCHAR2(25)
, UNIT_SYSTEM VARCHAR2(20)
, CONSTRAINT PK_FORMULA_NAME PRIMARY KEY(NAME)
, CONSTRAINT FK_FORMULA_UNIT_SYSTEM FOREIGN KEY(UNIT_SYSTEM) REFERENCES UNIT_SYSTEM(NAME)
);


CREATE OR REPLACE PACKAGE FORMULA_PKG AS
  -- Creates a new formula
  PROCEDURE NEW(PNAME IN FORMULA.NAME%TYPE, PUNIT IN FORMULA.UNIT_SYSTEM%TYPE DEFAULT 'IMPERIAL');
  
  -- Returns a single formula by name
  PROCEDURE GET(PNAME IN FORMULA.NAME%TYPE, PCURSOR OUT SYS_REFCURSOR);
  
  -- Returns all formulas
  PROCEDURE GET(PCURSOR OUT SYS_REFCURSOR);
  
END FORMULA_PKG;
/

CREATE OR REPLACE PACKAGE BODY FORMULA_PKG AS
  PROCEDURE NEW(PNAME IN FORMULA.NAME%TYPE, PUNIT IN FORMULA.UNIT_SYSTEM%TYPE DEFAULT 'IMPERIAL')
  IS
  BEGIN
    INSERT INTO FORMULA(NAME, UNIT_SYSTEM)
    VALUES(UPPER(PNAME), UPPER(PUNIT));
    COMMIT;
    
    EXCEPTION
      WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
  END NEW;
  
  PROCEDURE GET(PNAME IN FORMULA.NAME%TYPE, PCURSOR OUT SYS_REFCURSOR)
  IS
  BEGIN
    OPEN PCURSOR FOR
      SELECT *
      FROM FORMULA
      WHERE NAME=PNAME;
  END GET;
  
  PROCEDURE GET(PCURSOR OUT SYS_REFCURSOR)
  IS
  BEGIN
    OPEN PCURSOR FOR
      SELECT *
      FROM FORMULA;
  END GET;
  
END FORMULA_PKG;
/





-----------------------------------------------------------------
-- Initial Data
---------------
EXEC FORMULA_PKG.NEW('MIFFLIN-ST JOER', 'METRIC');
EXEC FORMULA_PKG.NEW('HARRIS-BENEDICT');
EXEC FORMULA_PKG.NEW('SIMPLE MULTIPLIER');



SELECT WEIGHT_DATE FROM ACCOUNT_VIEW;

CREATE OR REPLACE VIEW MIFFLIN_ST_JOER
AS 
  SELECT ID, ROUND(MULTIPLIER_AMOUNT*(WEIGHT+HEIGHT-AGE+EXTRA),2) TDEE, WEIGHT_DATE
  FROM (SELECT ID, 10*WEIGHT/DECODE(UNIT,'IMPERIAL',2.2,1) WEIGHT, 6.25*HEIGHT*DECODE(UNIT,'IMPERIAL',2.54,1) HEIGHT,
               AGE*5 AGE, DECODE(GENDER,'MALE',5,-161) EXTRA, MULTIPLIER_AMOUNT, WEIGHT_DATE
        FROM ACCOUNT_VIEW)
WITH READ ONLY;

CREATE OR REPLACE VIEW HARRIS_BENEDICT
AS
  SELECT ID, ROUND(MULTIPLIER_AMOUNT*(EXTRA+WEIGHT+HEIGHT-AGE),2) TDEE, WEIGHT_DATE
  FROM (SELECT ID, WEIGHT*DECODE(GENDER,'MALE',6.23,4.35) WEIGHT, HEIGHT*DECODE(GENDER,'MALE',12.7,4.7) HEIGHT,
               AGE*DECODE(GENDER,'MALE',6.67,4.7) AGE, DECODE(GENDER,'MALE',66,655) EXTRA, MULTIPLIER_AMOUNT, WEIGHT_DATE
        FROM (SELECT ID, WEIGHT*DECODE(UNIT,'METRIC',2.2,1) WEIGHT, 
                     HEIGHT/DECODE(UNIT,'METRIC',2.54,1) HEIGHT, AGE, MULTIPLIER_AMOUNT, GENDER, WEIGHT_DATE
              FROM ACCOUNT_VIEW))
WITH READ ONLY;