CREATE TABLE GENDER
( ID INTEGER PRIMARY KEY
, NAME VARCHAR2(15)
);

CREATE SEQUENCE SEQ_GENDERID
START WITH 0
MINVALUE 0
INCREMENT BY 1
CACHE 20
NOCYCLE;

-------------------------------------------------------------------------------
-- GENDER STORED PROCEDURES
-------------------------------------------------------------------------------
CREATE OR REPLACE PROCEDURE GENDER_INSERT( PNAME IN VARCHAR2 )
IS
BEGIN
  INSERT INTO GENDER(ID, NAME)
  VALUES(SEQ_GENDERID.NEXTVAL, PNAME);
  COMMIT;
  
  EXCEPTION
    WHEN OTHERS THEN
      ROLLBACK;
      RAISE;
END;
/

CREATE OR REPLACE PROCEDURE GENDER_GETALL( PCURSOR OUT SYS_REFCURSOR )
IS
BEGIN
  OPEN PCURSOR FOR
    SELECT * FROM GENDER ORDER BY ID;
END;
/

CREATE OR REPLACE PROCEDURE GENDER_GET_BYID
( PID IN GENDER.ID%TYPE
, PCURSOR OUT SYS_REFCURSOR
)
IS
BEGIN
  OPEN PCURSOR FOR
    SELECT * FROM GENDER WHERE ID=PID;
END;
/

CREATE OR REPLACE PROCEDURE GENDER_GET_BYNAME
( PNAME IN GENDER.NAME%TYPE
, PCURSOR OUT SYS_REFCURSOR
)
IS
BEGIN
  OPEN PCURSOR FOR
    SELECT * FROM GENDER WHERE UPPER(NAME)=UPPER(PNAME);
END;
/

-------------------------------------------------------------------------------
-- GENDER DATA
-------------------------------------------------------------------------------
EXEC GENDER_INSERT('SELECT A GENDER');
EXEC GENDER_INSERT('MALE');
EXEC GENDER_INSERT('FEMALE');