--------------------------------------------------------------------------------
-- CREATES ALL THE TABLES FOR THE BETTERU USER
--
-- LAST MODIFIED: 28-FEB-14
--------------------------------------------------------------------------------
DROP TABLE WEIGHT;
DROP TABLE DAILY_INTAKE;
DROP TABLE DAILY_MEAL_INTAKE;
DROP TABLE CALORIE_SPLIT;
DROP TABLE MEAL_PART;
DROP TABLE MEAL;
DROP TABLE INGREDIENT;
DROP TABLE TEMP_ACCOUNT;
DROP TABLE ACCOUNT_SETTING;
DROP TABLE ACCOUNT;
DROP TABLE GENDER;
DROP TABLE MULTIPLIER;
DROP TABLE FOOD_UNIT;
DROP TABLE WEEKDAY;
DROP TABLE CATEGORY;
DROP TABLE BRAND;
DROP TABLE FORMULA;
DROP TABLE UNIT_SYSTEM;
--------------------------------------------------------------------------------
-- CREATE REFERENCE TABLES
CREATE TABLE GENDER
( NAME VARCHAR2(15)
, CONSTRAINT PK_GENDER PRIMARY KEY(NAME)
);

CREATE TABLE MULTIPLIER
( NAME VARCHAR2(30)
, AMOUNT NUMBER (4,3)
, CONSTRAINT PK_MULTIPLIER PRIMARY KEY (NAME)
);

CREATE TABLE WEEKDAY
( NAME VARCHAR2(22) NOT NULL
, DAY_OF_WEEK INTEGER NOT NULL
, CONSTRAINT PK_WEEKDAY PRIMARY KEY(NAME)
);

CREATE TABLE CATEGORY
( NAME VARCHAR2(40)
, CONSTRAINT PK_CATEGORY_NAME PRIMARY KEY(NAME)
);

CREATE TABLE FOOD_UNIT
( NAME VARCHAR2(8)
, LONG_NAME VARCHAR2(15)
, CONSTRAINT PK_FOOD_UNIT PRIMARY KEY(NAME)
);

CREATE TABLE UNIT_SYSTEM
( NAME VARCHAR2(20)
, CONSTRAINT PK_UNIT_SYSTEM PRIMARY KEY (NAME)
);

CREATE TABLE BRAND
( NAME VARCHAR2(40) NOT NULL
, CONSTRAINT PK_BRAND_NAME PRIMARY KEY (NAME)
);

--------------------------------------------------------------------------------
-- CREATE REMAINING TABLES
--------------------------------------------------------------------------------
CREATE TABLE FORMULA
( NAME VARCHAR2(25)
, UNIT_SYSTEM VARCHAR2(20)
, CONSTRAINT PK_FORMULA_NAME PRIMARY KEY(NAME)
, CONSTRAINT FK_FORMULA_UNIT_SYSTEM FOREIGN KEY(UNIT_SYSTEM) REFERENCES UNIT_SYSTEM(NAME)
);

CREATE TABLE TEMP_ACCOUNT
( ID INTEGER
, USERNAME VARCHAR2(60)
, PASSWORD CHAR(128)
, CODE     CHAR(32)
, CREATED  DATE
, CONSTRAINT PK_TEMP_ACCOUNT_ID PRIMARY KEY (ID)
, CONSTRAINT UC_TEMPACCOUNT_USERNAME UNIQUE(USERNAME)
);

CREATE TABLE ACCOUNT
( ID INTEGER NOT NULL
, USERNAME VARCHAR2(60) NOT NULL
, PASSWORD CHAR(128) NOT NULL
, BIRTHDAY DATE
, UNIT VARCHAR2(8)
, GENDER VARCHAR2(7)
, LAST_LOGIN DATE
, ACTIVE_SINCE DATE
, CONSTRAINT PK_ACCOUNT_ID PRIMARY KEY (ID)
, CONSTRAINT FK_UNIT FOREIGN KEY(UNIT) REFERENCES UNIT_SYSTEM(NAME)
, CONSTRAINT FK_GENDER FOREIGN KEY (GENDER) REFERENCES GENDER(NAME)
, CONSTRAINT UC_ACCOUNT_USERNAME UNIQUE(USERNAME)
);

CREATE TABLE ACCOUNT_SETTING
( ID INTEGER
, ACCOUNTID INTEGER
, WEEKDAY VARCHAR2(22)
, MULTIPLIER VARCHAR2(30)
, HEIGHT NUMBER(5,1)
, FORMULA VARCHAR2(20) DEFAULT 'MIFFLIN-ST JOER'
, DATE_CHANGED DATE
, CONSTRAINT PK_ACCOUNT_SETTING_ID PRIMARY KEY (ID)
, CONSTRAINT FK_ACTSET_ACCOUNTID FOREIGN KEY(ACCOUNTID) REFERENCES ACCOUNT(ID)
, CONSTRAINT FK_ACTSET_WEEKDAY FOREIGN KEY(WEEKDAY) REFERENCES WEEKDAY(NAME)
, CONSTRAINT FK_ACTSET_MULTIPLIER FOREIGN KEY(MULTIPLIER) REFERENCES MULTIPLIER(NAME)
, CONSTRAINT FK_ACTSET_FORMULA FOREIGN KEY(FORMULA) REFERENCES FORMULA(NAME)
);

CREATE TABLE INGREDIENT
( ID INTEGER NOT NULL
, NAME VARCHAR2(128) NOT NULL
, BRAND VARCHAR2(60) NOT NULL
, CATEGORY VARCHAR2(40) NOT NULL
, SERVING_SIZE NUMBER(6,3) NOT NULL
, SERVING_UNIT VARCHAR2(8) NOT NULL
, ALT_SERVING_SIZE NUMBER(6,3)
, ALT_SERVING_UNIT VARCHAR2(8)
, CALORIES NUMBER(6,2)
, FAT NUMBER(6,2)
, CARBS NUMBER(6,2)
, PROTEIN NUMBER(6,2)
, CONSTRAINT PK_INGREDIENT_ID PRIMARY KEY (ID)
, CONSTRAINT FK_BRAND FOREIGN KEY(BRAND) REFERENCES BRAND(NAME)
, CONSTRAINT FK_CATEGORY FOREIGN KEY(CATEGORY) REFERENCES CATEGORY(NAME)
, CONSTRAINT FK_SERVING_UNIT FOREIGN KEY(SERVING_UNIT) REFERENCES FOOD_UNIT(NAME)
, CONSTRAINT FK_ALT_SERVING_UNIT FOREIGN KEY(ALT_SERVING_UNIT) REFERENCES FOOD_UNIT(NAME)
, CONSTRAINT UC_NAME_BRAND UNIQUE(NAME, BRAND)
);

CREATE TABLE MEAL
( ID INTEGER NOT NULL
, NAME VARCHAR2(128) NOT NULL
, DESCRIPTION CLOB
, CONSTRAINT PK_MEAL_ID PRIMARY KEY (ID)
);

CREATE TABLE MEAL_PART
( ID INTEGER NOT NULL
, MEALID INTEGER
, INGREDIENTID INTEGER
, AMOUNT NUMBER(6,2)
, DEFAULT_UNIT CHAR(1)
, CONSTRAINT PK_MEAL_PART_ID PRIMARY KEY (ID)
, CONSTRAINT FK_MEAL_PART_MEALID FOREIGN KEY(MEALID) REFERENCES MEAL(ID)
, CONSTRAINT FK_MEAL_PART_INGREDIENTID FOREIGN KEY(INGREDIENTID) REFERENCES INGREDIENT(ID)
, CONSTRAINT CK_DEFAULT_UNIT_FLAG CHECK(DEFAULT_UNIT BETWEEN 0 AND 1)
);

CREATE TABLE WEIGHT
( WEIGHT_DATE DATE
, ACCOUNT_ID INTEGER
, WEIGHT DECIMAL(6,2)
, CALORIE_CHANGE NUMBER
, FAT_MULTIPLIER DECIMAL(3,2)
, CARB_MULTIPLIER DECIMAL(3,2)
, PROTEIN_MULTIPLIER DECIMAL(3,2) DEFAULT 1.00
, CONSTRAINT PK_WEIGHT PRIMARY KEY(WEIGHT_DATE, ACCOUNT_ID)
, CONSTRAINT FK_WEIGHT_ACTID FOREIGN KEY(ACCOUNT_ID) REFERENCES ACCOUNT(ID)
, CONSTRAINT CK_WEIGHT_FC_MULTS CHECK(DECODE(PROTEIN_MULTIPLIER,1,FAT_MULTIPLIER+CARB_MULTIPLIER,FAT_MULTIPLIER+CARB_MULTIPLIER+PROTEIN_MULTIPLIER)=1)
);

CREATE TABLE DAILY_INTAKE
( ID INTEGER NOT NULL
, ACCOUNT_ID INTEGER NOT NULL
, INTAKE_DATE DATE NOT NULL
, CALORIE_CHANGE INTEGER NOT NULL
, CONSTRAINT PK_DAILY_INTAKE_ID PRIMARY KEY(ID)
, CONSTRAINT UC_DAILY_INTAKE_ACTID_DATE UNIQUE(ACCOUNT_ID, INTAKE_DATE)
, CONSTRAINT FK_DAILY_INTAKE_ACTID FOREIGN KEY(ACCOUNT_ID) REFERENCES ACCOUNT(ID)
);

CREATE TABLE DAILY_MEAL_INTAKE
( ID INTEGER NOT NULL
, ACCOUNT_ID INTEGER NOT NULL
, INTAKE_DATE DATE NOT NULL
, MEAL_ID INTEGER NOT NULL
, CONSTRAINT PK_DAILY_MEAL_INTAKE_ID PRIMARY KEY(ID)
, CONSTRAINT FK_DAILY_MEAL_INTAKE_ACTID FOREIGN KEY(ACCOUNT_ID) REFERENCES ACCOUNT(ID)
, CONSTRAINT UC_DAILY_MEAL_INTAKE_ACTDATE UNIQUE(ACCOUNT_ID, INTAKE_DATE)
, CONSTRAINT FK_DAILY_MEAL_INTAKE_MEALID FOREIGN KEY(MEAL_ID) REFERENCES MEAL(ID)
);

CREATE TABLE CALORIE_SPLIT
( ID INTEGER
, NAME VARCHAR2(40)
, WORKOUT_MULTIPLIER DECIMAL(3,2)
, REST_MULTIPLIER DECIMAL(3,2)
, CONSTRAINT PK_CALORIE_SPLIT_ID PRIMARY KEY(ID)
);