-- Gets the age for an account from the birthday
CREATE OR REPLACE FUNCTION GETAGE(PBIRTHDAY IN DATE) RETURN INTEGER
IS
  IDATE DATE;
BEGIN
  IF PBIRTHDAY IS NULL THEN
    IDATE := SYSDATE;
  ELSE
    IDATE := PBIRTHDAY;
  END IF;
  RETURN TO_CHAR(SYSDATE,'YYYY')-TO_CHAR(IDATE,'YYYY');
END GETAGE;