START INIT_TABLES.SQL;
START INIT_SEQUENCES.SQL;
START INIT_FUNCTIONS.SQL;
START INIT_PACKAGES.SQL;
START INIT_VIEWS.SQL;
START INIT_PACKAGE_BODY.SQL;


-- I don't understand this. even with substring from 1-10, the size of the string is 40
ALTER TABLE CALORIE_SPLIT
ADD (ABBREVIATION VARCHAR2(40) GENERATED ALWAYS AS 
    (SUBSTR(CALORIE_SPLIT_PKG.FORABBR(WORKOUT_MULTIPLIER, REST_MULTIPLIER),1,10)));


START INIT_VALUES.SQL;

ALTER TABLE UNIT_SYSTEM READ ONLY;
ALTER TABLE WEEKDAY READ ONLY;
ALTER TABLE MULTIPLIER READ ONLY;
ALTER TABLE CATEGORY READ ONLY;

COMMIT;