--------------------------------------------------------------------------------
-- CREATES ALL THE SEQUENCES FOR THE BETTERU USER
--
-- LAST MODIFIED: 28-FEB-14
--------------------------------------------------------------------------------
DROP SEQUENCE SEQ_TEMP_ACCOUNT_ID;
DROP SEQUENCE SEQ_ACCOUNT_ID;
DROP SEQUENCE SEQ_ACCOUNT_SETTING_ID;
DROP SEQUENCE SEQ_MEAL_ID;
DROP SEQUENCE SEQ_MEAL_PART_ID;
DROP SEQUENCE SEQ_INGREDIENT_ID;
DROP SEQUENCE SEQ_CALORIE_SPLIT_ID;

CREATE SEQUENCE SEQ_TEMP_ACCOUNT_ID
START WITH 0
MINVALUE 0
INCREMENT BY 1
CACHE 20
NOCYCLE;

CREATE SEQUENCE SEQ_ACCOUNT_ID
START WITH 0
MINVALUE 0
INCREMENT BY 1
CACHE 20
NOCYCLE;

CREATE SEQUENCE SEQ_ACCOUNT_SETTING_ID
START WITH 0
MINVALUE 0
INCREMENT BY 1
CACHE 20
NOCYCLE;

CREATE SEQUENCE SEQ_INGREDIENT_ID
START WITH 0
MINVALUE 0
INCREMENT BY 1
CACHE 20
NOCYCLE;

CREATE SEQUENCE SEQ_MEAL_ID
START WITH 0
MINVALUE 0
INCREMENT BY 1
CACHE 20
NOCYCLE;

CREATE SEQUENCE SEQ_MEAL_PART_ID
START WITH 0
MINVALUE 0
INCREMENT BY 1
CACHE 20
NOCYCLE;

CREATE SEQUENCE SEQ_CALORIE_SPLIT_ID
START WITH 0
MINVALUE 0
INCREMENT BY 1
CACHE 20
NOCYCLE;

CREATE SEQUENCE SEQ_DAILY_INTAKE_ID
START WITH 0
MINVALUE 0
INCREMENT BY 1
CACHE 20
NOCYCLE;