-- Gets the age for an account from the birthday
CREATE OR REPLACE FUNCTION GETAGE(PBIRTHDAY IN DATE) RETURN INTEGER
IS
  IDATE DATE;
BEGIN
  IF PBIRTHDAY IS NULL THEN
    IDATE := SYSDATE;
  ELSE
    IDATE := PBIRTHDAY;
  END IF;
  RETURN TO_CHAR(SYSDATE,'YYYY')-TO_CHAR(IDATE,'YYYY');
END GETAGE;
/

-- Gets the start date for an account based on account id and the date given
CREATE OR REPLACE FUNCTION GETSTARTDATE(PID IN INTEGER, PDATE IN DATE) RETURN DATE
IS
  v_Account_DoW INTEGER;
  v_Date_DoW INTEGER;
BEGIN
  SELECT DAY_OF_WEEK INTO v_Account_DoW FROM ACCOUNT_VIEW, WEEKDAY WHERE ID=PID AND WEEKDAY.NAME=WEEKDAY;
  SELECT TO_CHAR(PDATE,'D')-1 INTO v_Date_DoW FROM DUAL;
  
  IF v_Date_Dow=v_Account_DoW THEN
    RETURN PDATE;
  ELSIF v_Date_Dow<v_Account_DoW THEN
    RETURN PDATE - 7 + v_Date_DoW;
  ELSE
    RETURN PDATE - (v_Date_DoW-v_Account_DoW);
  END IF;
END GETSTARTDATE;
/