CREATE TABLE MEAL
( ID INTEGER PRIMARY KEY
, NAME VARCHAR2(128)
, DESCRIPTION NCLOB
);


CREATE SEQUENCE SEQ_MEALID
START WITH 0
MINVALUE 0
INCREMENT BY 1
CACHE 20
NOCYCLE;


-----------------
-- MEAL VIEW
-----------------
CREATE OR REPLACE VIEW MEAL_VIEW AS
  SELECT ID, NAME, DESCRIPTION, TOTAL_CALORIES, TOTAL_FAT, TOTAL_CARBS, TOTAL_PROTEIN
  FROM (SELECT MEALID, 
               ROUND(SUM(TOTAL_CALORIES),2) TOTAL_CALORIES, 
               ROUND(SUM(TOTAL_FAT),2) TOTAL_FAT, 
               ROUND(SUM(TOTAL_CARBS),2) TOTAL_CARBS, 
               ROUND(SUM(TOTAL_PROTEIN),2) TOTAL_PROTEIN
        FROM MEALPART_VIEW
        GROUP BY MEALID) MPV
  JOIN MEAL M
  ON M.ID = MPV.MEALID;

-------------------------------------------------------------------------------
-- MEAL PROCEDURES
-------------------------------------------------------------------------------
CREATE OR REPLACE PROCEDURE MEAL_INSERT
( PNAME IN MEAL.NAME%TYPE
, PDESC IN MEAL.DESCRIPTION%TYPE
)
IS
BEGIN
  INSERT INTO MEAL(ID, NAME, DESCRIPTION)
  VALUES(SEQ_MEALID.NEXTVAL, PNAME, PDESC);
  COMMIT;
  
  EXCEPTION
    WHEN OTHERS THEN
      ROLLBACK;
      RAISE;
END;
/


CREATE OR REPLACE PROCEDURE MEAL_GET_BYID
( PID IN MEAL.ID%TYPE
, PCURSOR OUT SYS_REFCURSOR
)
IS
BEGIN
  OPEN PCURSOR FOR
    SELECT * FROM MEAL WHERE ID=PID;
END;
/

CREATE OR REPLACE PROCEDURE MEAL_GETALL(PCURSOR OUT SYS_REFCURSOR)
IS
BEGIN
  OPEN PCURSOR FOR 
    SELECT * FROM MEAL;
END;
/

CREATE OR REPLACE PROCEDURE MEAL_VIEW_GET_BYID
( PID IN MEAL.ID%TYPE
, PCURSOR OUT SYS_REFCURSOR
)
IS
BEGIN
  OPEN PCURSOR FOR
    SELECT * FROM MEAL_VIEW WHERE ID=PID;
END;
/

CREATE OR REPLACE PROCEDURE MEAL_VIEW_GETALL(PCURSOR OUT SYS_REFCURSOR)
IS
BEGIN
  OPEN PCURSOR FOR 
    SELECT * FROM MEAL_VIEW;
END;
/

