CREATE TABLE MULTIPLIER(NAME VARCHAR2(30), AMOUNT NUMBER (4,3), CONSTRAINT PK_MULTIPLIER PRIMARY KEY (NAME));

-------------------------------------------------------------------------------
-- MULTIPLIER PROCEDURES
-------------------------------------------------------------------------------
CREATE OR REPLACE PACKAGE MULTIPLIER_PKG AS
  -- Creates a new multiplier
  PROCEDURE NEW(PNAME IN MULTIPLIER.NAME%TYPE, PAMT IN MULTIPLIER.AMOUNT%TYPE);
  
  -- Returns a SYS_REFCURSOR for all multiplierss
  PROCEDURE GET(PCURSOR OUT SYS_REFCURSOR);
  
  -- Returns a SYS_REFCURSOR for the multiplier amount for multiplier name
  PROCEDURE GETAMOUNT( PNAME IN MULTIPLIER.NAME%TYPE
                     , PCURSOR OUT SYS_REFCURSOR
                     );
  
END MULTIPLIER_PKG;
/

CREATE OR REPLACE PACKAGE BODY MULTIPLIER_PKG AS
  PROCEDURE NEW(PNAME IN MULTIPLIER.NAME%TYPE, PAMT IN MULTIPLIER.AMOUNT%TYPE)
  IS
  BEGIN
    INSERT INTO MULTIPLIER(NAME, AMOUNT)
    VALUES(PNAME, PAMT);
    COMMIT;
    
    EXCEPTION
      WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
  END NEW;
  
  PROCEDURE GET(PCURSOR OUT SYS_REFCURSOR)
  IS
  BEGIN
    OPEN PCURSOR FOR
      SELECT *
      FROM MULTIPLIER;
  END GET; 
  
  PROCEDURE GETAMOUNT(PNAME IN MULTIPLIER.NAME%TYPE
                     , PCURSOR OUT SYS_REFCURSOR
                     )
  IS
  BEGIN
    OPEN  PCURSOR FOR
      SELECT AMOUNT FROM MULTIPLIER WHERE NAME=PNAME;
  END GETAMOUNT;
  
END MULTIPLIER_PKG;
/

-------------------------------------------------------------------------------
-- MULTIPLIER INITIAL DATA
-------------------------------------------------------------------------------
EXEC MULTIPLIER_PKG.NEW('SEDENTARY', 1.2);
EXEC MULTIPLIER_PKG.NEW('LIGHTLY ACTIVE', 1.375);
EXEC MULTIPLIER_PKG.NEW('MODERATELY ACTIVE', 1.55);
EXEC MULTIPLIER_PKG.NEW('VERY ACTIVE', 1.725);
EXEC MULTIPLIER_PKG.NEW('EXTREMELY ACTIVE', 1.9);