CREATE TABLE RECALC
( ID INTEGER PRIMARY KEY
, NAME VARCHAR2(22)
);

CREATE SEQUENCE SEQ_RECALCID
START WITH 0
MINVALUE 0
INCREMENT BY 1
CACHE 20
NOCYCLE;


-------------------------------------------------------------------------------
-- RECALC PROCEDURES
-------------------------------------------------------------------------------
CREATE OR REPLACE PROCEDURE RECALC_INSERT(PNAME IN VARCHAR2)
IS
BEGIN
  INSERT INTO RECALC(ID, NAME)
  VALUES(SEQ_RECALCID.NEXTVAL, PNAME);
  COMMIT;
  
  EXCEPTION
    WHEN OTHERS THEN
      ROLLBACK;
      RAISE;
END;
/

CREATE OR REPLACE PROCEDURE RECALC_GETALL(PCURSOR OUT SYS_REFCURSOR)
IS
BEGIN
  OPEN PCURSOR FOR
    SELECT * FROM RECALC ORDER BY ID;
END;
/

CREATE OR REPLACE PROCEDURE RECALC_GET_BYID
( PID IN RECALC.ID%TYPE
, PCURSOR OUT SYS_REFCURSOR
)
IS
BEGIN
  OPEN PCURSOR FOR
    SELECT * FROM RECALC WHERE ID=PID;
END;
/

CREATE OR REPLACE PROCEDURE RECALC_GET_BYNAME
( PNAME IN RECALC.NAME%TYPE
, PCURSOR OUT SYS_REFCURSOR
)
IS
BEGIN
  OPEN PCURSOR FOR
    SELECT * FROM RECALC WHERE UPPER(NAME)=UPPER(PNAME);
END;
/

-------------------------------------------------------------------------------
-- RECALC INITIAL DATA
-------------------------------------------------------------------------------
EXEC RECALC_INSERT('SELECT THE DAY OF WEEK');
EXEC RECALC_INSERT('SUNDAY');
EXEC RECALC_INSERT('MONDAY');
EXEC RECALC_INSERT('TUESDAY');
EXEC RECALC_INSERT('WEDNESDAY');
EXEC RECALC_INSERT('THURSDAY');
EXEC RECALC_INSERT('FRIDAY');
EXEC RECALC_INSERT('SATURDAY');