CREATE TABLE TEMP_ACCOUNT
( ID INTEGER PRIMARY KEY
, USERNAME VARCHAR2(60)
, PASSWORD CHAR(128)
, CODE     CHAR(32)
, CREATED  DATE
);



CREATE SEQUENCE SEQ_TEMP_ACCOUNTID
START WITH 0
MINVALUE 0
INCREMENT BY 1
CACHE 20
NOCYCLE;

-------------------------------------------------------------------------------
-- TEMP_ACCOUNT PROCEDURES
-------------------------------------------------------------------------------
CREATE OR REPLACE PROCEDURE TEMP_ACCOUNT_INSERT
( PUSER IN TEMP_ACCOUNT.USERNAME%TYPE
, PPASS IN TEMP_ACCOUNT.PASSWORD%TYPE
, PCODE IN TEMP_ACCOUNT.CODE%TYPE
)
IS
BEGIN
  INSERT INTO TEMP_ACCOUNT(ID, USERNAME, PASSWORD, CODE, CREATED)
  VALUES(SEQ_TEMP_ACCOUNTID.NEXTVAL, PUSER, PPASS, PCODE, SYSDATE);
  COMMIT;
  
  EXCEPTION
    WHEN OTHERS THEN
      ROLLBACK;
      RAISE;
END;
/

CREATE OR REPLACE PROCEDURE TEMP_ACCOUNT_GET_BYID
( PID IN TEMP_ACCOUNT.ID%TYPE
, PCURSOR OUT SYS_REFCURSOR
)
IS
BEGIN
  OPEN PCURSOR FOR
    SELECT * FROM TEMP_ACCOUNT WHERE ID=PID;
END;
/

CREATE OR REPLACE PROCEDURE TEMP_ACCOUNT_DELETE_BYID(PID IN TEMP_ACCOUNT.ID%TYPE)
IS
BEGIN
  DELETE FROM TEMP_ACCOUNT
  WHERE ID=PID;
  COMMIT;
  
  EXCEPTION
    WHEN OTHERS THEN
      ROLLBACK;
END;
/