CREATE TABLE UNIT_SYSTEM
( ID INTEGER PRIMARY KEY
, NAME VARCHAR2(20)
);

CREATE SEQUENCE SEQ_UNIT_SYSTEMID
START WITH 0
MINVALUE 0
INCREMENT BY 1
CACHE 20
NOCYCLE;

-------------------------------------------------------------------------------
-- UNIT_SYSTEM PROCEDURES
-------------------------------------------------------------------------------
CREATE OR REPLACE PROCEDURE UNIT_SYSTEM_INSERT(PNAME IN VARCHAR2)
IS
BEGIN
  INSERT INTO UNIT_SYSTEM(ID, NAME)
  VALUES(SEQ_UNIT_SYSTEMID.NEXTVAL, PNAME);
  COMMIT;
  
  EXCEPTION
    WHEN OTHERS THEN
      ROLLBACK;
      RAISE;
END;
/

CREATE OR REPLACE PROCEDURE UNIT_SYSTEM_GETALL(PCURSOR OUT SYS_REFCURSOR)
IS
BEGIN
  OPEN PCURSOR FOR
    SELECT * FROM UNIT_SYSTEM ORDER BY ID;
END;
/

CREATE OR REPLACE PROCEDURE UNIT_SYSTEM_GET_BYID
( PID IN UNIT_SYSTEM.ID%TYPE
, PCURSOR OUT SYS_REFCURSOR
)
IS
BEGIN
  OPEN PCURSOR FOR
    SELECT * FROM UNIT_SYSTEM WHERE ID=PID;
END;
/

CREATE OR REPLACE PROCEDURE UNIT_SYSTEM_GET_BYNAME
( PNAME IN UNIT_SYSTEM.NAME%TYPE
, PCURSOR OUT SYS_REFCURSOR
)
IS
BEGIN
  OPEN PCURSOR FOR
    SELECT * FROM UNIT_SYSTEM WHERE UPPER(NAME)=UPPER(PNAME);
END;
/

-------------------------------------------------------------------------------
-- UNIT_SYSTEM INITIAL DATA
-------------------------------------------------------------------------------
EXEC UNIT_SYSTEM_INSERT('SELECT A UNIT SYSTEM');
EXEC UNIT_SYSTEM_INSERT('IMPERIAL');
EXEC UNIT_SYSTEM_INSERT('METRIC');