CREATE TABLE WEEKDAY
( NAME VARCHAR2(22) NOT NULL
, DAY_OF_WEEK INTEGER NOT NULL
, CONSTRAINT PK_WEEKDAY PRIMARY KEY(NAME));

-------------------------------------------------------------------------------
-- RECALC PROCEDURES
-------------------------------------------------------------------------------
CREATE OR REPLACE PACKAGE WEEKDAY_PKG AS
  -- Creates a new WEEKDAY
  PROCEDURE NEW(PNAME IN WEEKDAY.NAME%TYPE);
  
  -- Returns a SYS_REFCURSOR for all WEEKDAYs
  PROCEDURE GET(PCURSOR OUT SYS_REFCURSOR);
  
  -- Returns a SYS_REFCURSOR for a weekday by name
  PROCEDURE GET(Pname IN WEEKDAY.name%TYPE, PCURSOR OUT SYS_REFCURSOR);
  
  --Returns a SYS_REFCURSOR for a weekday by day of week number
  PROCEDURE GET(PDOW IN WEEKDAY.DAY_OF_WEEK%TYPE, PCURSOR OUT SYS_REFCURSOR);
END WEEKDAY_PKG;
/

CREATE OR REPLACE PACKAGE BODY WEEKDAY_PKG AS
  PROCEDURE NEW(PNAME IN WEEKDAY.NAME%TYPE)
  IS
    INUM INTEGER;
  BEGIN
    SELECT COUNT(NAME) INTO INUM FROM WEEKDAY;
    INSERT INTO WEEKDAY(NAME, DAY_OF_WEEK)
    VALUES(PNAME, INUM);
    COMMIT;
    
    EXCEPTION
      WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
  END NEW;
  
  PROCEDURE GET(PCURSOR OUT SYS_REFCURSOR)
  IS
  BEGIN
    OPEN PCURSOR FOR
      SELECT *
      FROM WEEKDAY;
  END GET;
  
  PROCEDURE GET(PNAME IN WEEKDAY.NAME%TYPE, PCURSOR OUT SYS_REFCURSOR)
  IS
  BEGIN
    OPEN PCURSOR FOR
      SELECT *
      FROM WEEKDAY
      WHERE NAME=PNAME;
  END GET;
  
  PROCEDURE GET(PDOW IN WEEKDAY.DAY_OF_WEEK%TYPE, PCURSOR OUT SYS_REFCURSOR)
  IS
  BEGIN
    OPEN PCURSOR FOR
      SELECT *
      FROM WEEKDAY
      WHERE DAY_OF_WEEK=PDOW;
  END GET;
  
END WEEKDAY_PKG;
/
-------------------------------------------------------------------------------
-- RECALC INITIAL DATA
-------------------------------------------------------------------------------
EXEC WEEKDAY_PKG.NEW('SUNDAY');
EXEC WEEKDAY_PKG.NEW('MONDAY');
EXEC WEEKDAY_PKG.NEW('TUESDAY');
EXEC WEEKDAY_PKG.NEW('WEDNESDAY');
EXEC WEEKDAY_PKG.NEW('THURSDAY');
EXEC WEEKDAY_PKG.NEW('FRIDAY');
EXEC WEEKDAY_PKG.NEW('SATURDAY');


ALTER TABLE WEEKDAY READ ONLY;