CREATE TABLE WEIGHT
( WEIGHT_DATE DATE
, ACCOUNT_ID INTEGER
, WEIGHT DECIMAL(6,2)
, CALORIE_CHANGE NUMBER
, FAT_MULTIPLIER DECIMAL(3,2)
, CARB_MULTIPLIER DECIMAL(3,2)
, PROTEIN_MULTIPLIER DECIMAL(3,2) DEFAULT 1.00
, CONSTRAINT PK_WEIGHT PRIMARY KEY(WEIGHT_DATE, ACCOUNT_ID)
, CONSTRAINT FK_WEIGHT_ACTID FOREIGN KEY(ACCOUNT_ID) REFERENCES ACCOUNT(ID)
, CONSTRAINT CK_WEIGHT_FC_MULTS CHECK(DECODE(PROTEIN_MULTIPLIER,1,FAT_MULTIPLIER+CARB_MULTIPLIER,FAT_MULTIPLIER+CARB_MULTIPLIER+PROTEIN_MULTIPLIER)=1)
);

CREATE OR REPLACE PACKAGE WEIGHT_PKG AS
  -- Returns an person's weight for an account id and date given
  PROCEDURE GET(PID IN WEIGHT.ACCOUNT_ID%TYPE, PDATE IN WEIGHT.WEIGHT_DATE%TYPE, PCURSOR OUT SYS_REFCURSOR);
  
  -- Returns all records for a person's weight for an account id;
  PROCEDURE GET(PID IN WEIGHT.ACCOUNT_ID%TYPE, PCURSOR OUT SYS_REFCURSOR);
  
  -- Creates a new weight. The default weight_date is sysdate
  PROCEDURE NEW( PACTID IN WEIGHT.ACCOUNT_ID%TYPE
               , PWEIGHT IN WEIGHT.WEIGHT%TYPE
               , PCAL IN WEIGHT.CALORIE_CHANGE%TYPE
               , PFAT IN WEIGHT.FAT_MULTIPLIER%TYPE
               , PCARB IN WEIGHT.CARB_MULTIPLIER%TYPE
               , PPROT IN WEIGHT.PROTEIN_MULTIPLIER%TYPE DEFAULT 1
               , PDATE IN WEIGHT.WEIGHT_DATE%TYPE DEFAULT SYSDATE
               );
  
END WEIGHT_PKG;
/

CREATE OR REPLACE PACKAGE BODY WEIGHT_PKG AS
  -- Returns an person's weight for an account id and date given
  PROCEDURE GET(PID IN WEIGHT.ACCOUNT_ID%TYPE, PDATE IN WEIGHT.WEIGHT_DATE%TYPE, PCURSOR OUT SYS_REFCURSOR)
  IS
  BEGIN
    OPEN PCURSOR FOR
      SELECT *
      FROM WEIGHT
      WHERE ACCOUNT_ID=PID AND ROUND(WEIGHT_DATE,'DDD')=ROUND(PDATE,'DDD')
      ORDER BY WEIGHT_DATE;
  END GET;
  
  -- Returns all records for a person's weight for an account id;
  PROCEDURE GET(PID IN WEIGHT.ACCOUNT_ID%TYPE, PCURSOR OUT SYS_REFCURSOR)
  IS
  BEGIN
    OPEN PCURSOR FOR
      SELECT *
      FROM WEIGHT
      WHERE ACCOUNT_ID=PID
      ORDER BY WEIGHT_DATE;
  END GET;
  
  -- Creates a new weight. The default weight_date is sysdate
  PROCEDURE NEW( PACTID IN WEIGHT.ACCOUNT_ID%TYPE
               , PWEIGHT IN WEIGHT.WEIGHT%TYPE
               , PCAL IN WEIGHT.CALORIE_CHANGE%TYPE
               , PFAT IN WEIGHT.FAT_MULTIPLIER%TYPE
               , PCARB IN WEIGHT.CARB_MULTIPLIER%TYPE
               , PPROT IN WEIGHT.PROTEIN_MULTIPLIER%TYPE DEFAULT 1
               , PDATE IN WEIGHT.WEIGHT_DATE%TYPE DEFAULT SYSDATE
               )
  IS
  BEGIN
    INSERT INTO WEIGHT(WEIGHT_DATE,ACCOUNT_ID,WEIGHT,CALORIE_CHANGE,FAT_MULTIPLIER,CARB_MULTIPLIER,PROTEIN_MULTIPLIER)
    VALUES(PDATE,PACTID,PWEIGHT,PCAL,PFAT,PCARB,PPROT);
    COMMIT;
    
    EXCEPTION
      WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
  END NEW;
  
END WEIGHT_PKG;
/
