CREATE TABLESPACE JSPBETTERU_TEST_01
   DATAFILE 'jspbetteru_test_01.dat' SIZE 40M 
   ONLINE;

select dbms_metadata.get_ddl('USER', 'JSPBETTERU') FROM DUAL;
SELECT DBMS_METADATA.GET_GRANTED_DDL('ROLE_GRANT','') FROM DUAL;
SELECT DBMS_METADATA.GET_GRANTED_DDL('SYSTEM_GRANT','...') FROM DUAL;
SELECT DBMS_METADATA.GET_GRANTED_DDL('OBJECT_GRANT','...') FROM DUAL;